services:
  webserver:
    image: webserver-apache-${IMAGE_ENV:-${ENV}}-${APACHE_VERSION}${SETUP_IMAGE_SUFFIX:-}
    container_name: ${PROJECT_NAME}-${ENV}-webserver-apache-${APACHE_VERSION}
    mem_limit: ${WEB_CONTAINER_MEMORY:-256m}
    cpus: ${CONTAINER_CPUS:-2}
    logging:
      driver: json-file
      options:
        max-size: ${CONTAINER_LOG_MAX_SIZE:-10m}
        max-file: "${CONTAINER_LOG_MAX_FILES:-3}"
    restart: unless-stopped
    build:
      context: ${ROOT_DIRECTORY}
      dockerfile: ${ROOT_DIRECTORY}/docker/apache/Dockerfile
      target: env-${BUILD_ENV:-${ENV}}
      args:
        PROFILE: ${PROFILE}
        APACHE_VERSION: ${APACHE_VERSION}
    command: /usr/local/bin/init.sh '${DOMAIN}' '${DOCUMENT_ROOT}' '${ENV}'
    environment:
      HTTP_FORCE_HTTPS: ${HTTP_FORCE_HTTPS:-off}
      CACHE_MODE: ${CACHE_MODE:-off}
    depends_on:
      php-fpm:
        condition: service_healthy
    networks:
      - network_app
    volumes:
      - ${PROJECT_WEB_DIRECTORY}:/var/www/html/
      - ${PROJECT_DATA_DIRECTORY}/ssl/:/etc/ssl/certs/:ro
      - ${PROJECT_DOCKER_DIRECTORY}/config/apache/:/usr/local/apache2/conf/project/:ro
      - ${PROJECT_DOCKER_DIRECTORY}/config/apache/${ENV}/:/usr/local/apache2/conf/project.env/:ro
