ROOT_DIRECTORY:=$(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
ROOT_DIRECTORY:=$(abspath $(APP_DOCKER_DIRECTORY)/../../)
DOCKER_DIRECTORY:={docker_dir}

local:
	$(MAKE) -C $(DOCKER_DIRECTORY) local PROJECT_DIRECTORY=$(ROOT_DIRECTORY)
