<?php return array (
    'parameters' =>
        array (
            'database_host' => '%DATABASE_HOST%',
            'database_port' => '%DATABASE_PORT%',
            'database_name' => '%DATABASE_NAME%',
            'database_user' => '%DATABASE_USER%',
            'database_password' => '%DATABASE_PASSWORD%',
            'database_prefix' => 'ps_',
            'database_engine' => 'InnoDB',
            'mailer_transport' => 'smtp',
            'mailer_host' => '%MAILER_HOST%',
            'mailer_user' => '%MAILER_USER%',
            'mailer_password' => '%MAILER_PASSWORD%',
            'secret' => '%SHOP_SECRET%',
            'ps_caching' => 'CacheMemcache',
            'ps_cache_enable' => false,
            'ps_creation_date' => '2020-02-14',
            'locale' => 'en-US',
            'use_debug_toolbar' => true,
            'cookie_key' => '%SHOP_COOKIE_KEY%',
            'cookie_iv' => '%SHOP_COOKIE_IV%',
            'new_cookie_key' => '%SHOP_NEW_COOKIE_KEY%',
        ),
);
