services:
  nginx-proxy:
    image: nginx-proxy-${IMAGE_ENV:-${ENV}}-${NGINX_VERSION}${SETUP_IMAGE_SUFFIX:-}
    container_name: ${PROJECT_NAME}-${ENV}-nginx-proxy-${NGINX_VERSION}
    mem_limit: ${WEB_CONTAINER_MEMORY:-256m}
    cpus: ${CONTAINER_CPUS:-2}
    logging:
      driver: json-file
      options:
        max-size: ${CONTAINER_LOG_MAX_SIZE:-10m}
        max-file: "${CONTAINER_LOG_MAX_FILES:-3}"
    restart: unless-stopped
    build:
      context: ${ROOT_DIRECTORY}
      dockerfile: ${ROOT_DIRECTORY}/docker/nginx-proxy/Dockerfile
      target: env-${BUILD_ENV:-${ENV}}
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        ENV: ${BUILD_ENV:-${ENV}}
    command: /usr/local/bin/init.sh '${DOMAIN}' '${WHITELISTED_IP}' '${WEBSERVICE_TIMEOUT}'
    environment:
      SETUP_ENVIRONMENT: ${ENV}
      CACHE_MODE: ${CACHE_MODE:-off}
      SETUP_ENABLE_PMA: ${SETUP_ENABLE_PMA:-0}
      SETUP_ENABLE_MAILPIT: ${SETUP_ENABLE_MAILPIT:-0}
    volumes:
      - ${PROJECT_DATA_DIRECTORY}/ssl/:/etc/ssl/certs/:ro
      - ${PROJECT_DOCKER_DIRECTORY}/config/nginx-proxy/:/etc/nginx/project.d/:ro
      - ${PROJECT_DOCKER_DIRECTORY}/config/nginx-proxy/${ENV}/:/etc/nginx/project.d.env/:ro
    ports:
      - ${LOCALHOST_PORT}:80
      - ${LOCALHOST_PORT_SSL}:443
    depends_on:
      - webserver
    networks:
      network_app:
        aliases:
          - ${DOMAIN}
