#!/bin/bash
set -euo pipefail

domain="${1:-}"
document_root="${2:-}"
env="${3:-}"
ssl_dir="/etc/ssl/certs"
sites_conf="/usr/local/apache2/conf/sites.conf"

# ── Validate required args ────────────────────────────────────────────────────
if [[ -z "$domain" ]]; then
  echo "[init] ERROR: domain argument is required" >&2
  exit 1
fi

# ── Substitute domain placeholder ─────────────────────────────────────────────
sed -i "s/DOMAIN_VAR/${domain}/g" "$sites_conf"
echo "[init] Domain set to: ${domain}"

# ── Substitute document root (optional) ───────────────────────────────────────
if [[ -n "$document_root" && "$document_root" != "/" ]]; then
  # Strip any leading/trailing slashes for a clean sub-path
  document_root="${document_root#/}"
  document_root="${document_root%/}"
  sed -i "s#/var/www/html#/var/www/html/${document_root}#g" "$sites_conf"
  echo "[init] Document root set to: /var/www/html/${document_root}"
fi

# ── SSL certificate verification ─────────────────────────────────────────────
# Certs are generated by mkcert on the host and bind-mounted into the container.
cert_file="${ssl_dir}/domain.crt"
key_file="${ssl_dir}/domain.key"

if [[ -f "$cert_file" && -f "$key_file" ]]; then
  echo "[init] SSL: certificates found for ${domain}"
else
  echo "[init] ERROR: SSL certificates not found at ${ssl_dir}/" >&2
  exit 1
fi

# ── Export ENV_PROFILE for Apache <If> directives ────────────────────────────
if [[ -n "$env" ]]; then
  echo "SetEnv ENV_PROFILE ${env}" >> /usr/local/apache2/conf/httpd.conf
  export ENV_PROFILE="${env}"
  echo "[init] ENV_PROFILE set to: ${env}"
fi

# ── Start Apache ──────────────────────────────────────────────────────────────
echo "[init] Starting Apache httpd..."
exec httpd-foreground
