"""Prepare PhpStorm project metadata and a private native-Compose bridge."""

from datetime import datetime, timezone
import json
import os
from pathlib import Path
import re
import subprocess
import tempfile
import uuid
import xml.etree.ElementTree as ET


MARKER = "Generated by shared setup ide-init"


def xml_bytes(root):
    ET.indent(root, space="  ")
    return ET.tostring(root, encoding="utf-8", xml_declaration=True) + b"\n"


def component(root, name):
    found = root.find(f"component[@name='{name}']")
    return found if found is not None else ET.SubElement(root, "component", name=name)


def checked_path(project, relative):
    path = project.directory / relative
    if (any(p.is_symlink() for p in (path, *path.parents) if p != project.directory and p.is_relative_to(project.directory))
            or not path.resolve().is_relative_to(project.directory)):
        raise ValueError(f"Refusing an IDE output symlink/outside path: {path}")
    if path.exists() and not path.is_file():
        raise ValueError(f"IDE output must be a file: {path}")
    return path


def replace_file(path, contents, private=False):
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_bytes() == contents:
        if private:
            path.chmod(0o600)
        return
    with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as handle:
        temporary = Path(handle.name)
        handle.write(contents)
    try:
        temporary.chmod(0o600 if private else 0o644)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def refresh_ide(project):
    relative = f".generated/phpstorm-compose.{project.environment}.yaml"
    path = checked_path(project, relative)
    contents = project.capture(["config"]).encode()
    replace_file(path, contents, private=True)
    print(f"Refreshed private PhpStorm Compose file: {path}")
    return relative


def docker_server_name(config_directory=None):
    """Read existing Linux PhpStorm connections; never edit global IDE settings."""
    if config_directory:
        directories = [Path(config_directory)]
    else:
        base = Path(os.environ.get("XDG_CONFIG_HOME", str(Path.home() / ".config"))) / "JetBrains"
        directories = sorted(base.glob("PhpStorm*"), key=lambda p: [int(n) for n in re.findall(r"\d+", p.name)], reverse=True)
    try:
        result = subprocess.run(["docker", "context", "inspect", "--format", "{{.Endpoints.docker.Host}}"],
                                capture_output=True, text=True, timeout=10)
        endpoint = result.stdout.strip() if result.returncode == 0 else ""
        if not os.environ.get("DOCKER_CONTEXT"):
            endpoint = os.environ.get("DOCKER_HOST") or endpoint
    except (OSError, subprocess.TimeoutExpired):
        endpoint = ""
    for directory in directories:
        config = directory / "options/remote-servers.xml"
        if not config.is_file():
            continue
        try:
            root = ET.parse(config).getroot()
        except ET.ParseError:
            continue
        for server in root.iter("remote-server"):
            option = server.find(".//option[@name='apiUrl']")
            if server.get("type") != "docker" or option is None:
                continue
            address = option.get("value", "").replace("$USER_HOME$", str(Path.home()))
            if endpoint and address == endpoint:
                return server.get("name", "Docker"), True
    return "Docker", False


def ide_plan(project, server):
    """Merge project components, retaining unrelated settings and run configs."""
    originals, outputs, deletions = {}, {}, []

    def read(relative):
        path = checked_path(project, relative)
        originals[relative] = path.read_bytes() if path.exists() else None
        return originals[relative]

    def document(relative):
        contents = read(relative)
        try:
            return ET.fromstring(contents) if contents else ET.Element("project", version="4")
        except ET.ParseError as error:
            raise ValueError(f"Invalid existing IDE XML; preserved: {relative}") from error

    model = json.loads(project.capture(["config", "--format", "json"]))
    php = model["services"].get("php-fpm")
    if not php:
        raise ValueError("ide-init requires the php-fpm service")
    version = str(php.get("build", {}).get("args", {}).get("PHP_VERSION", ""))
    if not re.fullmatch(r"\d+\.\d+(?:\.\d+)?", version):
        raise ValueError("Set PHP_VERSION in the PHP service build arguments for ide-init")
    version = ".".join(version.split(".")[:2])
    name = project.settings["PROJECT_NAME"]
    interpreter_name = f"{project.name} PHP"
    display_name = project.settings.get('PROJECT_DISPLAY_NAME') or name
    outputs[".idea/.name"] = (display_name + "\n").encode()
    read(".idea/.name")

    modules = document(".idea/modules.xml")
    manager = component(modules, "ProjectModuleManager")
    entries = manager.find("modules")
    if entries is None:
        entries = ET.SubElement(manager, "modules")
    module_file = f".idea/{name}.iml"
    old_module = None
    for entry in entries.findall("module"):
        location = entry.get("filepath", "")
        if location in (f"$PROJECT_DIR$/{module_file}", f"$PROJECT_DIR$/../{module_file}"):
            old_module = module_file
            break
        if len(entries) == 1 and location == "$PROJECT_DIR$/.idea/docker.iml":
            old_module = ".idea/docker.iml"
            entry.set("filepath", f"$PROJECT_DIR$/{module_file}")
            entry.set("fileurl", f"file://$PROJECT_DIR$/{module_file}")
            if old_module != module_file:
                deletions.append(old_module)
            break
    if not len(entries):
        ET.SubElement(entries, "module", fileurl=f"file://$PROJECT_DIR$/{module_file}", filepath=f"$PROJECT_DIR$/{module_file}")
    elif old_module is None:
        # Custom multi-module projects keep their existing module definitions.
        module_file = None
    if module_file:
        contents = read(old_module or module_file)
        module = ET.fromstring(contents) if contents else ET.Element("module", type="WEB_MODULE", version="4")
        roots = component(module, "NewModuleRootManager")
        content = roots.find("content")
        if content is None:
            content = ET.SubElement(roots, "content")
        content.set("url", "file://$PROJECT_DIR$")
        for source in list(content.findall("sourceFolder")):
            if source.get("url", "").endswith("/examples/php-redis/database/doctrine/versions") and not (project.directory / "examples/php-redis/database/doctrine/versions").exists():
                content.remove(source)
        for relative in (".generated", "public/var/cache", "public/var/logs"):
            url = f"file://$PROJECT_DIR$/{relative}"
            if content.find(f"excludeFolder[@url='{url}']") is None:
                ET.SubElement(content, "excludeFolder", url=url)
        if roots.find("orderEntry") is None:
            ET.SubElement(roots, "orderEntry", type="inheritedJdk")
            ET.SubElement(roots, "orderEntry", type="sourceFolder", forTests="false")
        outputs[module_file] = xml_bytes(module)
        if module_file not in originals:
            if read(module_file) is not None:
                raise ValueError(f"Existing destination module preserved: {module_file}")
    outputs[".idea/modules.xml"] = xml_bytes(modules)

    vcs = document(".idea/vcs.xml")
    mappings = component(vcs, "VcsDirectoryMappings")
    for directory in (project.directory, project.root / "app/public"):
        if (directory / ".git").exists():
            relative = os.path.relpath(directory, project.directory)
            value = "$PROJECT_DIR$" + ("/" + relative if relative != "." else "")
            existing = next((m for m in mappings.findall("mapping") if m.get("directory") in (value, "" if relative == "." else value)), None)
            if existing is None:
                ET.SubElement(mappings, "mapping", directory=value, vcs="Git")
    outputs[".idea/vcs.xml"] = xml_bytes(vcs)

    php_config = document(".idea/php.xml")
    component(php_config, "PhpProjectSharedConfiguration").set("php_language_level", version)
    interpreters = component(php_config, "PhpInterpreters")
    entries = interpreters.find("interpreters")
    if entries is None:
        entries = ET.SubElement(interpreters, "interpreters")
    identifier = str(uuid.uuid5(uuid.NAMESPACE_URL, f"shared-setup:{interpreter_name}"))
    for entry in list(entries):
        if entry.get("id") == identifier:
            entries.remove(entry)
        elif entry.get("name") == interpreter_name:
            raise ValueError(f"An unrelated interpreter already uses {interpreter_name}; preserved")
    interpreter = ET.SubElement(entries, "interpreter", id=identifier, name=interpreter_name,
                                home="docker-compose://DATA", auto="false", debugger_id="php.debugger.XDebug")
    remote = ET.SubElement(interpreter, "remote_data", INTERPRETER_PATH="/usr/local/bin/php",
                           HELPERS_PATH="/opt/.phpstorm_helpers", VALID="true", RUN_AS_ROOT_VIA_SUDO="false",
                           DOCKER_ACCOUNT_NAME=server, DOCKER_COMPOSE_SERVICE_NAME="php-fpm",
                           DOCKER_REMOTE_PROJECT_PATH="/var/www/html")
    ET.SubElement(remote, "type_data", command="EXEC")
    paths = ET.SubElement(remote, "dockerComposeConfigurationPaths")
    ET.SubElement(paths, "item", value=f"$PROJECT_DIR$/.generated/phpstorm-compose.{project.environment}.yaml")
    envs = ET.SubElement(remote, "envs")
    ET.SubElement(envs, "env", name="COMPOSE_PROJECT_NAME", value=project.name)
    ET.SubElement(envs, "env", name="COMPOSE_DISABLE_ENV_FILE", value="true")
    ET.SubElement(envs, "env", name="COMPOSE_PROFILES", value=project.profiles)
    outputs[".idea/php.xml"] = xml_bytes(php_config)

    workspace = document(".idea/workspace.xml")
    component(workspace, "PhpWorkspaceProjectConfiguration").set("interpreter_name", interpreter_name)
    outputs[".idea/workspace.xml"] = xml_bytes(workspace)

    actions = [("prepare_ide", "Prepare IDE", "ide-init"), ("up", "Start", "up"),
               ("down", "Stop", "down"), ("check", "Check", "doctor"), ("shell", "PHP shell", "shell")]
    if project.settings["SCHEMA_DIRECTORY"]:
        actions += [("schema_export", "Export schema", "schema-export"), ("schema_check", "Check schema", "schema-check")]
    for key, label, action in actions:
        relative = f".idea/runConfigurations/setup_{key}.xml"
        contents = read(relative)
        if contents and MARKER.encode() not in contents:
            existing = ET.fromstring(contents).find("configuration")
            # PhpStorm drops XML comments when saving. The reserved file/name
            # pair still identifies our configurations after an IDE round trip.
            if existing is None or existing.get("name") != f"Setup: {label}" or existing.get("type") != "ShConfigurationType":
                raise ValueError(f"Existing user run configuration preserved: {relative}")
        root = ET.Element("component", name="ProjectRunConfigurationManager")
        root.append(ET.Comment(MARKER))
        run = ET.SubElement(root, "configuration", default="false", name=f"Setup: {label}", type="ShConfigurationType")
        options = {"SCRIPT_TEXT": f"make ENV={project.environment} {action}", "SCRIPT_PATH": "", "SCRIPT_OPTIONS": "",
                   "SCRIPT_WORKING_DIRECTORY": "$PROJECT_DIR$", "INTERPRETER_PATH": "/bin/sh", "INTERPRETER_OPTIONS": "",
                   "EXECUTE_IN_TERMINAL": "true" if action == "shell" else "false", "EXECUTE_SCRIPT_FILE": "false"}
        for key, value in options.items():
            ET.SubElement(run, "option", name=key, value=value)
            if key in ("SCRIPT_PATH", "SCRIPT_WORKING_DIRECTORY", "INTERPRETER_PATH"):
                ET.SubElement(run, "option", name="INDEPENDENT_" + key, value=value)
        ET.SubElement(run, "method", v="2")
        outputs[relative] = xml_bytes(root)
    startup = document(".idea/startup.xml")
    entries = component(startup, "ProjectStartupSharedConfiguration")
    configurations = entries.find("configurations")
    if configurations is None:
        configurations = ET.SubElement(entries, "configurations")
    if configurations.find("configuration[@name='Setup: Prepare IDE']") is None:
        ET.SubElement(configurations, "configuration", id="Shell Script.Setup: Prepare IDE", name="Setup: Prepare IDE")
    outputs[".idea/startup.xml"] = xml_bytes(startup)
    return originals, outputs, deletions


def initialize_ide(project, docker_server=None, config_directory=None):
    server, detected = (docker_server, True) if docker_server else docker_server_name(config_directory)
    originals, outputs, deletions = ide_plan(project, server)
    # Validate every destination before writing anything, including the private bridge.
    checked_path(project, f".generated/phpstorm-compose.{project.environment}.yaml")
    for relative in outputs:
        checked_path(project, relative)
    for relative, before in originals.items():
        path = checked_path(project, relative)
        if (path.read_bytes() if path.exists() else None) != before:
            raise ValueError(f"IDE settings changed during preparation; retry: {relative}")
    changed = {name for name, contents in outputs.items() if originals.get(name) != contents} | set(deletions)
    if changed:
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%f")
        for name in changed:
            if originals.get(name) is not None:
                backup = checked_path(project, f".generated/phpstorm-backups/{stamp}/{name}")
                replace_file(backup, originals[name], private=True)
    refresh_ide(project)
    for name, contents in outputs.items():
        replace_file(checked_path(project, name), contents, private=name == ".idea/workspace.xml")
    for name in deletions:
        checked_path(project, name).unlink(missing_ok=True)
    print(f"Prepared PhpStorm: {project.settings.get('PROJECT_DISPLAY_NAME') or project.settings['PROJECT_NAME']}; interpreter {project.name} PHP; Docker connection {server}.")
    if not detected:
        print("Create the Docker connection named Docker in PhpStorm, or rerun with --docker-server NAME.")
    print("Startup only refreshes IDE settings; services and DB imports run only when explicitly selected.")
