services:
  mailpit:
    image: mailpit-${IMAGE_ENV:-${ENV}}-${MAILPIT_VERSION}${SETUP_IMAGE_SUFFIX:-}
    container_name: ${PROJECT_NAME}-${ENV}-mailpit-${MAILPIT_VERSION}
    profiles:
      - mailpit
    mem_limit: ${WEB_CONTAINER_MEMORY:-256m}
    cpus: ${CONTAINER_CPUS:-2}
    logging:
      driver: json-file
      options:
        max-size: ${CONTAINER_LOG_MAX_SIZE:-10m}
        max-file: "${CONTAINER_LOG_MAX_FILES:-3}"
    restart: unless-stopped
    build:
      context: ${ROOT_DIRECTORY}
      dockerfile: ${ROOT_DIRECTORY}/docker/mailpit/Dockerfile
      target: env-${BUILD_ENV:-${ENV}}
      args:
        MAILPIT_VERSION: ${MAILPIT_VERSION}
    environment:
      TZ: Europe/Vilnius
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - network_app
    volumes:
      - ${PROJECT_DATA_DIRECTORY}/mailpit/:/data
