CREATE USER IF NOT EXISTS 'exporter'@'localhost' IDENTIFIED BY '{EXPORTER_PASSWORD}' WITH MAX_USER_CONNECTIONS 3;
GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'%' IDENTIFIED BY '{EXPORTER_PASSWORD}' WITH GRANT OPTION;
FLUSH PRIVILEGES;
