CREATE USER IF NOT EXISTS '{DATABASE_USER}'@'localhost' IDENTIFIED BY '{DATABASE_PASSWORD}';
GRANT ALL PRIVILEGES ON {DATABASE_NAME}.* TO '{DATABASE_USER}'@'%' IDENTIFIED BY '{DATABASE_PASSWORD}' WITH GRANT OPTION;

CREATE USER IF NOT EXISTS 'exporter'@'localhost' IDENTIFIED BY '{EXPORTER_PASSWORD}' WITH MAX_USER_CONNECTIONS 3;
GRANT ALL PRIVILEGES ON *.* TO 'exporter'@'%' IDENTIFIED BY '{EXPORTER_PASSWORD}' WITH GRANT OPTION;
--GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'%' IDENTIFIED BY '{EXPORTER_PASSWORD}' WITH GRANT OPTION;

FLUSH PRIVILEGES;
