# Production data is separate from existing local data.
services:
  database:
    volumes:
      - ${PROJECT_DATA_DIRECTORY}/prod/mysql:/var/lib/mysql
  mailpit:
    volumes:
      - ${PROJECT_DATA_DIRECTORY}/prod/mailpit:/data
  nginx-proxy:
    volumes:
      - ${PROJECT_DATA_DIRECTORY}/prod/ssl:/etc/ssl/certs:ro
  php-cs:
    volumes:
      - ${PROJECT_DATA_DIRECTORY}/prod/php-cs:/tmp/php-cs-fixer/cache
  php-fpm:
    volumes:
      - ${PROJECT_DATA_DIRECTORY}/prod/profiling:/tmp/profiling
  php-phpstan:
    volumes:
      - ${PROJECT_DATA_DIRECTORY}/prod/phpstan:/tmp/phpstan/cache
  playwright:
    volumes:
      - ${PROJECT_DATA_DIRECTORY}/prod/playwright:/e2e/data
  webserver:
    volumes:
      - ${PROJECT_DATA_DIRECTORY}/prod/ssl:/etc/ssl/certs:ro
  php-doctrine-migrations:
    volumes:
      - ${PROJECT_DATA_DIRECTORY}/prod/doctrine-migrations:/tmp/doctrine-migrations/cache
