; Runtime defaults, followed by project and environment-specific *.ini overrides.
opcache.enable = ${PHP_OPCACHE}
opcache.enable_cli = 0
opcache.validate_timestamps = ${PHP_OPCACHE_VALIDATE_TIMESTAMPS}
opcache.revalidate_freq = ${PHP_OPCACHE_REVALIDATE_FREQ}
opcache.file_cache =
apc.enabled = ${PHP_APCU}
apc.enable_cli = 0
